CREATE SEQUENCE articulo_key_sequence --SECUENCIA PARA CODIGO DEL ARTICULO EN LA TABLA ARTICULO 
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE repuesto_key_sequence --SECUENCIA PARA EL NUMERO DE VENTA EN LA TABLA REPUESTO 
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE herramienta_key_sequence --SECUENCIA PARA CODIGO DE LA HERRAMIENTA DE LA TABLA HERRAMIENTA 
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE marca_key_sequence --SECUENCIA EL CAMPO AUTOINCREMENTAL NUMERO DE LA MARCA DE LA TABLA MARCA
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE modelo_key_sequence --SECUENCIA EL CAMPO AUTOINCREMENTAL NUMERO DEL MODELO DE LA TABLA MODELO
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE orden_key_sequence --SECUENCIA EL CAMPO AUTOINCREMENTAL NUMERO DEL MODELO DE LA TABLA ORDEN
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE factura_compra_key_sequence --SECUENCIA PARA EL NUMERO DE VENTA EN LA TABLA FACTURA_COMPRA
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE factura_venta_key_sequence --SECUENCIA PARA EL NUMERO DE FACTURA EN LA FACTURA_VENTA
	START WITH 1
	INCREMENT BY 1;

CREATE SEQUENCE venta_web_key_sequence --SECUENCIA PARA EL NUMERO DE VENTA EN LA TABLA VENTA_WEB 
	START WITH 1
	INCREMENT BY 1;