DROP TRIGGER articulo_key_trigger ;
DROP TRIGGER repuesto_key_trigger ;
DROP TRIGGER herramienta_key_trigger ;
DROP TRIGGER marca_key_trigger ;
DROP TRIGGER modelo_key_trigger ;
DROP TRIGGER orden_key_trigger ;
DROP TRIGGER factura_compra_key_trigger ;
DROP TRIGGER factura_venta_key_trigger ;
DROP TRIGGER venta_web_key_trigger ;
DROP TRIGGER detalles_fv_trigger;
DROP TRIGGER detalles_fc_art_trigger;
DROP TRIGGER detalles_fc_rep_trigger;
DROP TRIGGER detalles_fc_herr_trigger;
DROP TRIGGER uso_rep_insert_trigger;
DROP TRIGGER uso_rep_update_trigger;
DROP TRIGGER orden_estado_trigger;
DROP TRIGGER articulo_venta_web;
DROP TRIGGER cuenta_por_pagar_saldo;
DROP TRIGGER cuenta_por_cobrar_saldo;
DROP TRIGGER marca_foreign_key;
DROP TRIGGER equipo_foreign_key;
DROP TRIGGER repuesto_foreign_key;
DROP TRIGGER articulo_foreign_key;
DROP TRIGGER herramienta_foreign_key;